name: Test native code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run native tests
      working-directory: ./app/src/main/jni/tests
      run: ./run_tests.sh
